CC = gcc
CFLAGS = -Wall -Wextra -I.
LDFLAGS = -lMLV

SOURCES = main.c taquin.c affichage.c
OBJECTS = $(SOURCES:.c=.o)
TARGET = taquin

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)
